### ISSUE TITLE
lang trans for gui

### ISSUE THREAD

**Issue by gedw99** [gedw99/sc-gio#1]
@mearaj i think you have worked on this in your project ?

https://github.com/gedw99/sc-gio/tree/main/sheet/amplify-edge__shared described what we have to help.

**Comment by mearaj** [comment]
> @mearaj i think you have worked on this in your project ?
> 
> https://github.com/gedw99/sc-gio/tree/main/sheet/amplify-edge__shared described what we have to help.

Yeah correct. :)
